import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { defaultParameters, getNodeMetadata } from '../../src/nodes/registry';

test('flags invalid typed values with a field-level validation message in the config panel', async ({ page, request }, info) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const workflow = await (await request.post('/api/workflows', { data: { name: 'Validation proof' } })).json();
  workflow.nodes = [{ id: 'validate', type: 'httpRequest', name: 'Validate', position: { x: 0, y: 0 }, parameters: defaultParameters(getNodeMetadata('httpRequest')!), credentials: {} }];
  await request.put('/api/workflows/' + workflow.id, { data: workflow });
  await page.goto('/');
  await page.getByTestId('workflow-list').getByRole('button', { name: workflow.name, exact: true }).click();
  await page.locator('[data-id="validate"]').click();
  const timeout = page.getByTestId('param-timeout');
  await expect(timeout).toHaveValue('30000');
  await timeout.fill('700000');
  await expect(page.getByTestId('field-error-timeout')).toContainText('between 1 and 300000');
  await page.getByTestId('save-workflow').click();
  await expect(page.getByTestId('status')).toContainText('Invalid');
  const persisted = await (await request.get('/api/workflows/' + workflow.id)).json();
  expect(persisted.nodes[0].parameters.timeout).toBe(30000);
  await timeout.fill('45000');
  await expect(page.getByTestId('field-error-timeout')).toHaveCount(0);
  await page.getByTestId('save-workflow').click();
  await expect(page.getByTestId('status')).toContainText('Saved');
  expect(errors).toEqual([]);
  await info.attach('errors', { body: JSON.stringify(errors), contentType: 'application/json' });
});

test('inspects persisted execution data and logs after reload', async ({ page, request }, info) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const workflow = await (await request.post('/api/workflows', { data: { name: 'Inspector proof' } })).json();
  workflow.nodes = ['manualTrigger', 'set', 'set'].map((type, i) => ({ id: `inspect${i}`, type, name: `Step ${i}`, position: { x: i * 240, y: 100 }, credentials: {}, parameters: defaultParameters(getNodeMetadata(type)!) }));
  workflow.nodes[1].parameters.value = 'hello';
  workflow.nodes[2].parameters.value = '{{$json.missing}}';
  workflow.connections = [0, 1].map(i => ({ id: `inspectEdge${i}`, source: `inspect${i}`, target: `inspect${i + 1}`, sourcePort: 'main', targetPort: 'main' }));
  await request.put('/api/workflows/' + workflow.id, { data: workflow });
  await page.goto('/');
  await page.getByTestId('workflow-list').getByRole('button', { name: workflow.name, exact: true }).click();
  await page.getByTestId('run-workflow').click();
  await expect(page.getByTestId('execution-result')).toContainText('error');
  await page.reload();
  await page.getByTestId('workflow-list').getByRole('button', { name: workflow.name, exact: true }).click();
  await expect(page.getByTestId('execution-select').locator('option')).toHaveCount(2);
  const history = await (await request.get(`/api/workflows/${workflow.id}/executions`)).json();
  await page.getByTestId('execution-select').selectOption(history[0].executionId);
  await page.getByTestId('inspect-node').selectOption('inspect1');
  await expect(page.getByTestId('inspect-input')).toHaveText('{}');
  await expect(page.getByTestId('inspect-output')).toContainText('hello');
  await expect(page.getByTestId('inspect-parameters')).toContainText('hello');
  await expect(page.getByTestId('inspect-duration')).toContainText('ms');
  await page.getByTestId('inspect-node').selectOption('inspect2');
  await expect(page.getByTestId('inspect-input')).toContainText('hello');
  await expect(page.getByTestId('inspect-error')).toHaveText('Missing own property: missing');
  await expect(page.getByTestId('execution-logs')).toContainText('node.error');
  await expect(page.getByTestId('execution-logs')).toContainText('workflow.error');
  await page.screenshot({ path: 'evidence/phase3/inspector.png' });
  expect(errors).toEqual([]);
  await info.attach('errors', { body: JSON.stringify(errors), contentType: 'application/json' });
});

test('imports and exports workflow JSON through the editor without overwriting', async ({ page, request }) => {
  const workflow = await (await request.post('/api/workflows', { data: { name: 'Transfer proof' } })).json();
  await page.goto('/');
  await page.getByTestId('workflow-list').getByRole('button', { name: workflow.name, exact: true }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByTestId('export-workflow').click();
  const download = await downloadPromise;
  const raw = await readFile((await download.path())!, 'utf8');
  expect(JSON.parse(raw).id).toBe(workflow.id);
  await page.getByTestId('import-workflow').setInputFiles({ name: 'workflow.json', mimeType: 'application/json', buffer: Buffer.from(raw) });
  await expect(page.getByTestId('status')).toContainText('Imported');
  await expect(page.getByTestId('workflow-list').getByRole('button', { name: workflow.name, exact: true })).toHaveCount(2);
  const before = await (await request.get('/api/workflows')).json();
  await page.getByTestId('import-workflow').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{bad') });
  await expect(page.getByTestId('status')).toContainText('Invalid JSON');
  expect(await (await request.get('/api/workflows')).json()).toEqual(before);
});
